### ISSUE TITLE
Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

### ISSUE THREAD

**Issue by devin91** [rosjava/android_core#292]
I have use ROS for one years and one mouth ago , I have used the android core package to develop an application for my robot, It run well.
    last week , I want update my application ,but I found the android core package has update ,and I built this package,There is some issues like this:
BUILD SUCCESSFUL in 26s
218 actionable tasks: 218 executed
Built target gradle-android_core

FAILURE: Build failed with an exception.

* Where:
Script 'https://github.com/rosjava/rosjava_bootstrap/raw/kinetic/buildscript.gradle' line: 44

* What went wrong:
A problem occurred evaluating script.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

so , Is there some bug with the latest package or some sdk need to update?

**Comment by jubeira** [comment]
Hi @devin91, please see https://github.com/rosjava/rosjava_bootstrap/issues/78; this error is because you need an updated Gradle version with the latest changes introduced in #286 and related PRs.

**Comment by zhicheng93** [comment]
hi, when u upgrade the new version. i cannot run the program called map nav. I tried to upgrade gradle to 4.10.2, then i got following problems.
Unable to resolve dependency for make_a_map@kineticDebug.compileClassPath':Could not find any version that matches com.github.rosjava.android_remocons:common_tools:[0.3,0.4)
Unable to resolve dependency for make_a_map@kineticDebug.compileClassPath':Could not find any version that matches org.ros.android_core:android_core_components:[0.4,0.5)

Any hits? thanks @jubeira

**Comment by zhicheng93** [comment]
i tried to find the component.aar and commontool.aar, then use them as my external libraries. Build well but has this following mistake.
java.lang.NoClassDefFoundError: failed resolution of: Lcom/github/robotics_in_concert/recon_rosjava_core/rocon_interactions/InteractionMode;

I just download your program called android_apps(version kinetic) and did not change any codes. @jubeira

**Comment by jubeira** [comment]
Hi @zhicheng93,
You are trying to build `android_apps` on its own right? I mean, you don't have `android_core` nor `android_remocons` built from source do you?
The artifacts for `android_core_components[0.4, 0.5)` and `remocons:common_tools[0.3, 0.4)` were merged into `rosjava_mvn_repo` just now; see https://github.com/rosjava/rosjava_mvn_repo/pull/62. Could you please try again now?

**Comment by zhicheng93** [comment]
@jubeira  fixed it. thanks for your reply

**Comment by zhicheng93** [comment]
hi, @jubeira ,
i just find another error. When i connect to the master, the program will quit and give me following error. I use the original android_apps and still get this error. Is there any other details i missed?

<img width="906" alt="image" src="https://user-images.githubusercontent.com/46367278/50760480-eeafa080-12a2-11e9-943b-7d329f07b7d0.png">

**Comment by jubeira** [comment]
@zhicheng93 sorry for the delay; this seems like a different issue, can you open a new one to track it down?

If you make a fix please send a PR so we can keep improving the code. Thanks!

**Comment by gongyue666** [comment]
hi, I download the rosjava_build_tools whose gradle is 4.10.2 and source the workspace which this pkg is, and then catkin_make the android_core, but still have this error. Do I do something wrong?PLZ help

**Comment by jubeira** [comment]
@gongyue666 that should work; please try starting with a fresh rosjava installation.
I'd recommend you to:
- Install rosjava from [source](http://wiki.ros.org/rosjava/Tutorials/kinetic/Source%20Installation).
- Source the workspace with the installation.
- Clone `android_core` in a separate workspace.
- Build `android_core`'s workspace using `catkin_make`.

Those basic steps should work; please let me know otherwise.

**Comment by gongyue666** [comment]
Hi,thx for your reply.I do as follow:
1 make worksapce named rosjava and install follow with section 3.1 of this website http://wiki.ros.org/rosjava/Tutorials/kinetic/Source%20Installation . catkint_make finished but get some warnings: warning: [options] bootstrap class path not set in conjunction with 1.6 and warning: [options] bootstrap class path not set in conjunction with 1.7.it's the problem??
2 build android_core
2.0:make worksapce named android_core, mkdir -p ~/android_core/src && cd ~/android_core/src/
2.1:git clone https://github.com/rosjava/android_core.git
2.2:source ~/rosjave_core/devel/setup.bash
2.3:cd ~/android_core && catkin_make , and here I got error can not get 'android.support.v7.app', then I add "classpath "com.android.support:appcompat-v7:28.0.0" in buildscript.gradle.and then I re-catkin_make , and get the error:Could not find method google() for arguments []    ~_~

**Comment by jubeira** [comment]
You shouldn't need to add anything when you build the first time.
Try building with Gradle instead of catkin. Go to the root directory where you cloned `android_core` and run `./gradlew build --debug`. That should give you a hint about what's going on there. Do you have a firewall or something that might be preventing Gradle from reaching certain URLs?

**Comment by gongyue666** [comment]
Thx for your reply, I use ./gradlew build --debug to re-compile the android_core and it build successfully with some warnings that loses some XXUnitTestXXX. I think it is just a little case.Thx。
